// Maps lowercased team name variants → logo URL.
// API-Football CDN: https://media.api-sports.io/football/teams/{id}.png (public, no auth needed)
// flagcdn.com: https://flagcdn.com/48x36/{iso2}.webp (public, no auth needed)
const RAW: [string, string][] = [
  // ─── English Premier League ──────────────────────────────────────────────
  ["ав",                  "https://media.api-sports.io/football/teams/66.png"],   // Aston Villa
  ["астон вилла",        "https://media.api-sports.io/football/teams/66.png"],
  ["арсенал",            "https://media.api-sports.io/football/teams/42.png"],
  ["борнмут",            "https://media.api-sports.io/football/teams/35.png"],
  ["вх",                 "https://media.api-sports.io/football/teams/48.png"],   // West Ham
  ["кп",                 "https://media.api-sports.io/football/teams/52.png"],   // Crystal Palace
  ["кристал пелас",      "https://media.api-sports.io/football/teams/52.png"],
  ["кристал пелес",      "https://media.api-sports.io/football/teams/52.png"],
  ["кристал пэлас",      "https://media.api-sports.io/football/teams/52.png"],
  ["лидс",               "https://media.api-sports.io/football/teams/63.png"],
  ["ливерпуль",          "https://media.api-sports.io/football/teams/40.png"],
  ["мю",                 "https://media.api-sports.io/football/teams/33.png"],   // Manchester United
  ["ман ю",              "https://media.api-sports.io/football/teams/33.png"],
  ["ман сити",           "https://media.api-sports.io/football/teams/50.png"],   // Manchester City
  ["ман сіті",           "https://media.api-sports.io/football/teams/50.png"],
  ["манчестер сити",     "https://media.api-sports.io/football/teams/50.png"],
  ["манчестер",          "https://media.api-sports.io/football/teams/33.png"],
  ["ньюкасл",            "https://media.api-sports.io/football/teams/34.png"],
  ["ньюкасал",           "https://media.api-sports.io/football/teams/34.png"],
  ["ньюксал",            "https://media.api-sports.io/football/teams/34.png"],
  ["тотенхем",           "https://media.api-sports.io/football/teams/47.png"],
  ["тотенхэм",           "https://media.api-sports.io/football/teams/47.png"],
  ["тоттенхэм",          "https://media.api-sports.io/football/teams/47.png"],
  ["ттх",                "https://media.api-sports.io/football/teams/47.png"],   // Tottenham abbrev
  ["челси",              "https://media.api-sports.io/football/teams/49.png"],
  ["чесли",              "https://media.api-sports.io/football/teams/49.png"],
  ["эвертон",            "https://media.api-sports.io/football/teams/45.png"],

  // ─── La Liga ─────────────────────────────────────────────────────────────
  ["атлетик",            "https://media.api-sports.io/football/teams/531.png"],  // Athletic Bilbao
  ["атлетик б",          "https://media.api-sports.io/football/teams/531.png"],
  ["бильбао",            "https://media.api-sports.io/football/teams/531.png"],
  ["атлетико",           "https://media.api-sports.io/football/teams/530.png"],  // Atletico Madrid
  ["атлетико б",         "https://media.api-sports.io/football/teams/530.png"],
  ["атлетико м",         "https://media.api-sports.io/football/teams/530.png"],
  ["атм",                "https://media.api-sports.io/football/teams/530.png"],
  ["барса",              "https://media.api-sports.io/football/teams/529.png"],  // Barcelona
  ["барселона",          "https://media.api-sports.io/football/teams/529.png"],
  ["бетис",              "https://media.api-sports.io/football/teams/543.png"],  // Real Betis
  ["вельяреал",          "https://media.api-sports.io/football/teams/533.png"],  // Villarreal
  ["вильяреал",          "https://media.api-sports.io/football/teams/533.png"],
  ["вильяреалл",         "https://media.api-sports.io/football/teams/533.png"],
  ["райо",               "https://media.api-sports.io/football/teams/728.png"],  // Rayo Vallecano
  ["реал",               "https://media.api-sports.io/football/teams/541.png"],  // Real Madrid
  ["реал сосьедад",      "https://media.api-sports.io/football/teams/548.png"],

  // ─── Bundesliga ──────────────────────────────────────────────────────────
  ["бавария",            "https://media.api-sports.io/football/teams/157.png"],
  ["баер",               "https://media.api-sports.io/football/teams/168.png"],  // Bayer Leverkusen
  ["бд",                 "https://media.api-sports.io/football/teams/165.png"],  // Borussia Dortmund
  ["боруссия д",         "https://media.api-sports.io/football/teams/165.png"],
  ["рбл",                "https://media.api-sports.io/football/teams/173.png"],  // RB Leipzig
  ["фрайбург",           "https://media.api-sports.io/football/teams/160.png"],
  ["штутгарт",           "https://media.api-sports.io/football/teams/172.png"],

  // ─── Serie A ─────────────────────────────────────────────────────────────
  ["ам",                 "https://media.api-sports.io/football/teams/489.png"],  // AC Milan
  ["милан",              "https://media.api-sports.io/football/teams/489.png"],
  ["аталанта",           "https://media.api-sports.io/football/teams/499.png"],
  ["интер",              "https://media.api-sports.io/football/teams/505.png"],
  ["комо",               "https://media.api-sports.io/football/teams/511.png"],
  ["лацио",              "https://media.api-sports.io/football/teams/487.png"],
  ["наполи",             "https://media.api-sports.io/football/teams/492.png"],
  ["рома",               "https://media.api-sports.io/football/teams/497.png"],
  ["ювентус",            "https://media.api-sports.io/football/teams/496.png"],

  // ─── Ligue 1 ─────────────────────────────────────────────────────────────
  ["псж",                "https://media.api-sports.io/football/teams/85.png"],
  ["лион",               "https://media.api-sports.io/football/teams/80.png"],
  ["марсель",            "https://media.api-sports.io/football/teams/81.png"],
  ["монако",             "https://media.api-sports.io/football/teams/91.png"],
  ["страсбург",          "https://media.api-sports.io/football/teams/95.png"],

  // ─── Other European clubs ─────────────────────────────────────────────────
  ["бенфика",            "https://media.api-sports.io/football/teams/211.png"],
  ["галатасарай",        "https://media.api-sports.io/football/teams/213.png"],
  ["шахтер",             "https://media.api-sports.io/football/teams/503.png"],  // Shakhtar Donetsk

  // ─── National teams (English names from The Odds API / OddsPapi imports) ─
  // Africa
  ["algeria",                    "https://flagcdn.com/48x36/dz.webp"],
  ["angola",                     "https://flagcdn.com/48x36/ao.webp"],
  ["benin",                      "https://flagcdn.com/48x36/bj.webp"],
  ["botswana",                   "https://flagcdn.com/48x36/bw.webp"],
  ["burkina faso",               "https://flagcdn.com/48x36/bf.webp"],
  ["burundi",                    "https://flagcdn.com/48x36/bi.webp"],
  ["cameroon",                   "https://flagcdn.com/48x36/cm.webp"],
  ["cape verde",                 "https://flagcdn.com/48x36/cv.webp"],
  ["central african republic",   "https://flagcdn.com/48x36/cf.webp"],
  ["chad",                       "https://flagcdn.com/48x36/td.webp"],
  ["comoros",                    "https://flagcdn.com/48x36/km.webp"],
  ["congo",                      "https://flagcdn.com/48x36/cg.webp"],
  ["congo dr",                   "https://flagcdn.com/48x36/cd.webp"],
  ["democratic republic of congo","https://flagcdn.com/48x36/cd.webp"],
  ["djibouti",                   "https://flagcdn.com/48x36/dj.webp"],
  ["egypt",                      "https://flagcdn.com/48x36/eg.webp"],
  ["equatorial guinea",          "https://flagcdn.com/48x36/gq.webp"],
  ["eritrea",                    "https://flagcdn.com/48x36/er.webp"],
  ["ethiopia",                   "https://flagcdn.com/48x36/et.webp"],
  ["gabon",                      "https://flagcdn.com/48x36/ga.webp"],
  ["gambia",                     "https://flagcdn.com/48x36/gm.webp"],
  ["ghana",                      "https://flagcdn.com/48x36/gh.webp"],
  ["guinea",                     "https://flagcdn.com/48x36/gn.webp"],
  ["guinea-bissau",              "https://flagcdn.com/48x36/gw.webp"],
  ["ivory coast",                "https://flagcdn.com/48x36/ci.webp"],
  ["côte d'ivoire",              "https://flagcdn.com/48x36/ci.webp"],
  ["kenya",                      "https://flagcdn.com/48x36/ke.webp"],
  ["lesotho",                    "https://flagcdn.com/48x36/ls.webp"],
  ["liberia",                    "https://flagcdn.com/48x36/lr.webp"],
  ["libya",                      "https://flagcdn.com/48x36/ly.webp"],
  ["madagascar",                 "https://flagcdn.com/48x36/mg.webp"],
  ["malawi",                     "https://flagcdn.com/48x36/mw.webp"],
  ["mali",                       "https://flagcdn.com/48x36/ml.webp"],
  ["mauritania",                 "https://flagcdn.com/48x36/mr.webp"],
  ["mauritius",                  "https://flagcdn.com/48x36/mu.webp"],
  ["morocco",                    "https://flagcdn.com/48x36/ma.webp"],
  ["mozambique",                 "https://flagcdn.com/48x36/mz.webp"],
  ["namibia",                    "https://flagcdn.com/48x36/na.webp"],
  ["niger",                      "https://flagcdn.com/48x36/ne.webp"],
  ["nigeria",                    "https://flagcdn.com/48x36/ng.webp"],
  ["rwanda",                     "https://flagcdn.com/48x36/rw.webp"],
  ["senegal",                    "https://flagcdn.com/48x36/sn.webp"],
  ["sierra leone",               "https://flagcdn.com/48x36/sl.webp"],
  ["somalia",                    "https://flagcdn.com/48x36/so.webp"],
  ["south africa",               "https://flagcdn.com/48x36/za.webp"],
  ["south sudan",                "https://flagcdn.com/48x36/ss.webp"],
  ["sudan",                      "https://flagcdn.com/48x36/sd.webp"],
  ["tanzania",                   "https://flagcdn.com/48x36/tz.webp"],
  ["togo",                       "https://flagcdn.com/48x36/tg.webp"],
  ["tunisia",                    "https://flagcdn.com/48x36/tn.webp"],
  ["uganda",                     "https://flagcdn.com/48x36/ug.webp"],
  ["zambia",                     "https://flagcdn.com/48x36/zm.webp"],
  ["zimbabwe",                   "https://flagcdn.com/48x36/zw.webp"],

  // Asia
  ["afghanistan",                "https://flagcdn.com/48x36/af.webp"],
  ["bahrain",                    "https://flagcdn.com/48x36/bh.webp"],
  ["bangladesh",                 "https://flagcdn.com/48x36/bd.webp"],
  ["bhutan",                     "https://flagcdn.com/48x36/bt.webp"],
  ["cambodia",                   "https://flagcdn.com/48x36/kh.webp"],
  ["china",                      "https://flagcdn.com/48x36/cn.webp"],
  ["china pr",                   "https://flagcdn.com/48x36/cn.webp"],
  ["hong kong",                  "https://flagcdn.com/48x36/hk.webp"],
  ["india",                      "https://flagcdn.com/48x36/in.webp"],
  ["indonesia",                  "https://flagcdn.com/48x36/id.webp"],
  ["iran",                       "https://flagcdn.com/48x36/ir.webp"],
  ["iraq",                       "https://flagcdn.com/48x36/iq.webp"],
  ["israel",                     "https://flagcdn.com/48x36/il.webp"],
  ["japan",                      "https://flagcdn.com/48x36/jp.webp"],
  ["jordan",                     "https://flagcdn.com/48x36/jo.webp"],
  ["kuwait",                     "https://flagcdn.com/48x36/kw.webp"],
  ["kyrgyzstan",                 "https://flagcdn.com/48x36/kg.webp"],
  ["laos",                       "https://flagcdn.com/48x36/la.webp"],
  ["lebanon",                    "https://flagcdn.com/48x36/lb.webp"],
  ["macau",                      "https://flagcdn.com/48x36/mo.webp"],
  ["malaysia",                   "https://flagcdn.com/48x36/my.webp"],
  ["maldives",                   "https://flagcdn.com/48x36/mv.webp"],
  ["mongolia",                   "https://flagcdn.com/48x36/mn.webp"],
  ["myanmar",                    "https://flagcdn.com/48x36/mm.webp"],
  ["nepal",                      "https://flagcdn.com/48x36/np.webp"],
  ["north korea",                "https://flagcdn.com/48x36/kp.webp"],
  ["oman",                       "https://flagcdn.com/48x36/om.webp"],
  ["pakistan",                   "https://flagcdn.com/48x36/pk.webp"],
  ["palestine",                  "https://flagcdn.com/48x36/ps.webp"],
  ["philippines",                "https://flagcdn.com/48x36/ph.webp"],
  ["qatar",                      "https://flagcdn.com/48x36/qa.webp"],
  ["saudi arabia",               "https://flagcdn.com/48x36/sa.webp"],
  ["singapore",                  "https://flagcdn.com/48x36/sg.webp"],
  ["south korea",                "https://flagcdn.com/48x36/kr.webp"],
  ["sri lanka",                  "https://flagcdn.com/48x36/lk.webp"],
  ["syria",                      "https://flagcdn.com/48x36/sy.webp"],
  ["tajikistan",                 "https://flagcdn.com/48x36/tj.webp"],
  ["thailand",                   "https://flagcdn.com/48x36/th.webp"],
  ["timor-leste",                "https://flagcdn.com/48x36/tl.webp"],
  ["turkmenistan",               "https://flagcdn.com/48x36/tm.webp"],
  ["united arab emirates",       "https://flagcdn.com/48x36/ae.webp"],
  ["uzbekistan",                 "https://flagcdn.com/48x36/uz.webp"],
  ["vietnam",                    "https://flagcdn.com/48x36/vn.webp"],
  ["yemen",                      "https://flagcdn.com/48x36/ye.webp"],

  // Europe
  ["albania",                    "https://flagcdn.com/48x36/al.webp"],
  ["andorra",                    "https://flagcdn.com/48x36/ad.webp"],
  ["armenia",                    "https://flagcdn.com/48x36/am.webp"],
  ["austria",                    "https://flagcdn.com/48x36/at.webp"],
  ["azerbaijan",                 "https://flagcdn.com/48x36/az.webp"],
  ["belarus",                    "https://flagcdn.com/48x36/by.webp"],
  ["belgium",                    "https://flagcdn.com/48x36/be.webp"],
  ["bosnia and herzegovina",     "https://flagcdn.com/48x36/ba.webp"],
  ["bulgaria",                   "https://flagcdn.com/48x36/bg.webp"],
  ["croatia",                    "https://flagcdn.com/48x36/hr.webp"],
  ["cyprus",                     "https://flagcdn.com/48x36/cy.webp"],
  ["czech republic",             "https://flagcdn.com/48x36/cz.webp"],
  ["czechia",                    "https://flagcdn.com/48x36/cz.webp"],
  ["denmark",                    "https://flagcdn.com/48x36/dk.webp"],
  ["england",                    "https://flagcdn.com/48x36/gb-eng.webp"],
  ["estonia",                    "https://flagcdn.com/48x36/ee.webp"],
  ["faroe islands",              "https://flagcdn.com/48x36/fo.webp"],
  ["finland",                    "https://flagcdn.com/48x36/fi.webp"],
  ["france",                     "https://flagcdn.com/48x36/fr.webp"],
  ["georgia",                    "https://flagcdn.com/48x36/ge.webp"],
  ["germany",                    "https://flagcdn.com/48x36/de.webp"],
  ["gibraltar",                  "https://flagcdn.com/48x36/gi.webp"],
  ["greece",                     "https://flagcdn.com/48x36/gr.webp"],
  ["hungary",                    "https://flagcdn.com/48x36/hu.webp"],
  ["iceland",                    "https://flagcdn.com/48x36/is.webp"],
  ["ireland",                    "https://flagcdn.com/48x36/ie.webp"],
  ["republic of ireland",        "https://flagcdn.com/48x36/ie.webp"],
  ["italy",                      "https://flagcdn.com/48x36/it.webp"],
  ["kazakhstan",                 "https://flagcdn.com/48x36/kz.webp"],
  ["kosovo",                     "https://flagcdn.com/48x36/xk.webp"],
  ["latvia",                     "https://flagcdn.com/48x36/lv.webp"],
  ["liechtenstein",              "https://flagcdn.com/48x36/li.webp"],
  ["lithuania",                  "https://flagcdn.com/48x36/lt.webp"],
  ["luxembourg",                 "https://flagcdn.com/48x36/lu.webp"],
  ["malta",                      "https://flagcdn.com/48x36/mt.webp"],
  ["moldova",                    "https://flagcdn.com/48x36/md.webp"],
  ["monaco",                     "https://flagcdn.com/48x36/mc.webp"],
  ["montenegro",                 "https://flagcdn.com/48x36/me.webp"],
  ["netherlands",                "https://flagcdn.com/48x36/nl.webp"],
  ["north macedonia",            "https://flagcdn.com/48x36/mk.webp"],
  ["northern ireland",           "https://flagcdn.com/48x36/gb-nir.webp"],
  ["norway",                     "https://flagcdn.com/48x36/no.webp"],
  ["poland",                     "https://flagcdn.com/48x36/pl.webp"],
  ["portugal",                   "https://flagcdn.com/48x36/pt.webp"],
  ["romania",                    "https://flagcdn.com/48x36/ro.webp"],
  ["russia",                     "https://flagcdn.com/48x36/ru.webp"],
  ["san marino",                 "https://flagcdn.com/48x36/sm.webp"],
  ["scotland",                   "https://flagcdn.com/48x36/gb-sct.webp"],
  ["serbia",                     "https://flagcdn.com/48x36/rs.webp"],
  ["slovakia",                   "https://flagcdn.com/48x36/sk.webp"],
  ["slovenia",                   "https://flagcdn.com/48x36/si.webp"],
  ["spain",                      "https://flagcdn.com/48x36/es.webp"],
  ["sweden",                     "https://flagcdn.com/48x36/se.webp"],
  ["switzerland",                "https://flagcdn.com/48x36/ch.webp"],
  ["turkey",                     "https://flagcdn.com/48x36/tr.webp"],
  ["ukraine",                    "https://flagcdn.com/48x36/ua.webp"],
  ["wales",                      "https://flagcdn.com/48x36/gb-wls.webp"],

  // North & Central America + Caribbean
  ["antigua and barbuda",        "https://flagcdn.com/48x36/ag.webp"],
  ["aruba",                      "https://flagcdn.com/48x36/aw.webp"],
  ["bahamas",                    "https://flagcdn.com/48x36/bs.webp"],
  ["barbados",                   "https://flagcdn.com/48x36/bb.webp"],
  ["belize",                     "https://flagcdn.com/48x36/bz.webp"],
  ["bermuda",                    "https://flagcdn.com/48x36/bm.webp"],
  ["canada",                     "https://flagcdn.com/48x36/ca.webp"],
  ["cayman islands",             "https://flagcdn.com/48x36/ky.webp"],
  ["costa rica",                 "https://flagcdn.com/48x36/cr.webp"],
  ["cuba",                       "https://flagcdn.com/48x36/cu.webp"],
  ["curaçao",                    "https://flagcdn.com/48x36/cw.webp"],
  ["curacao",                    "https://flagcdn.com/48x36/cw.webp"],
  ["dominica",                   "https://flagcdn.com/48x36/dm.webp"],
  ["dominican republic",         "https://flagcdn.com/48x36/do.webp"],
  ["el salvador",                "https://flagcdn.com/48x36/sv.webp"],
  ["grenada",                    "https://flagcdn.com/48x36/gd.webp"],
  ["guadeloupe",                 "https://flagcdn.com/48x36/gp.webp"],
  ["guatemala",                  "https://flagcdn.com/48x36/gt.webp"],
  ["guyana",                     "https://flagcdn.com/48x36/gy.webp"],
  ["haiti",                      "https://flagcdn.com/48x36/ht.webp"],
  ["honduras",                   "https://flagcdn.com/48x36/hn.webp"],
  ["jamaica",                    "https://flagcdn.com/48x36/jm.webp"],
  ["martinique",                 "https://flagcdn.com/48x36/mq.webp"],
  ["mexico",                     "https://flagcdn.com/48x36/mx.webp"],
  ["nicaragua",                  "https://flagcdn.com/48x36/ni.webp"],
  ["panama",                     "https://flagcdn.com/48x36/pa.webp"],
  ["puerto rico",                "https://flagcdn.com/48x36/pr.webp"],
  ["saint kitts and nevis",      "https://flagcdn.com/48x36/kn.webp"],
  ["saint lucia",                "https://flagcdn.com/48x36/lc.webp"],
  ["saint vincent and the grenadines","https://flagcdn.com/48x36/vc.webp"],
  ["suriname",                   "https://flagcdn.com/48x36/sr.webp"],
  ["trinidad and tobago",        "https://flagcdn.com/48x36/tt.webp"],
  ["united states",              "https://flagcdn.com/48x36/us.webp"],
  ["usa",                        "https://flagcdn.com/48x36/us.webp"],
  ["us virgin islands",          "https://flagcdn.com/48x36/vi.webp"],
  ["virgin islands, us",         "https://flagcdn.com/48x36/vi.webp"],
  ["virgin islands, british",    "https://flagcdn.com/48x36/vg.webp"],
  ["british virgin islands",     "https://flagcdn.com/48x36/vg.webp"],

  // South America
  ["argentina",                  "https://flagcdn.com/48x36/ar.webp"],
  ["bolivia",                    "https://flagcdn.com/48x36/bo.webp"],
  ["brazil",                     "https://flagcdn.com/48x36/br.webp"],
  ["chile",                      "https://flagcdn.com/48x36/cl.webp"],
  ["colombia",                   "https://flagcdn.com/48x36/co.webp"],
  ["ecuador",                    "https://flagcdn.com/48x36/ec.webp"],
  ["paraguay",                   "https://flagcdn.com/48x36/py.webp"],
  ["peru",                       "https://flagcdn.com/48x36/pe.webp"],
  ["uruguay",                    "https://flagcdn.com/48x36/uy.webp"],
  ["venezuela",                  "https://flagcdn.com/48x36/ve.webp"],

  // Oceania
  ["australia",                  "https://flagcdn.com/48x36/au.webp"],
  ["fiji",                       "https://flagcdn.com/48x36/fj.webp"],
  ["guam",                       "https://flagcdn.com/48x36/gu.webp"],
  ["new caledonia",              "https://flagcdn.com/48x36/nc.webp"],
  ["new zealand",                "https://flagcdn.com/48x36/nz.webp"],
  ["papua new guinea",           "https://flagcdn.com/48x36/pg.webp"],
  ["samoa",                      "https://flagcdn.com/48x36/ws.webp"],
  ["solomon islands",            "https://flagcdn.com/48x36/sb.webp"],
  ["tahiti",                     "https://flagcdn.com/48x36/pf.webp"],
  ["tonga",                      "https://flagcdn.com/48x36/to.webp"],
  ["vanuatu",                    "https://flagcdn.com/48x36/vu.webp"],
]

export const TEAM_LOGO_MAP = new Map<string, string>(RAW)

export function getTeamLogoUrl(teamName: string): string | undefined {
  return TEAM_LOGO_MAP.get(teamName.toLowerCase().trim())
}
